# Generated by Django 5.1.3 on 2024-11-13 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='name',
        ),
        migrations.RemoveField(
            model_name='country',
            name='name',
        ),
        migrations.RemoveField(
            model_name='state',
            name='name',
        ),
        migrations.AddField(
            model_name='city',
            name='city_name',
            field=models.CharField(default='Unknown Detail', max_length=100),
        ),
        migrations.AddField(
            model_name='city',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='continent',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='country_code',
            field=models.CharField(default='Unknown', max_length=3, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='country',
            name='country_name',
            field=models.CharField(default='Unknown Detail', max_length=100),
        ),
        migrations.AddField(
            model_name='state',
            name='state_name',
            field=models.CharField(default='Unknown Detail', max_length=100),
        ),
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_date', models.DateField()),
                ('temperature_high', models.FloatField()),
                ('temperature_low', models.FloatField()),
                ('weather_description', models.CharField(blank=True, max_length=255, null=True)),
                ('humidity', models.FloatField(blank=True, null=True)),
                ('wind_speed', models.FloatField(blank=True, null=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather.city')),
            ],
        ),
        migrations.DeleteModel(
            name='Weather',
        ),
    ]
